In [1]:
import numpy as np

In [3]:
matrix = np.matrix([1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape(3,3)
matrix


matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [4]:
teste = matrix[1, 1]
teste

matrix([[4, 5, 6]])

In [8]:
teste = 1

In [9]:
teste

1

In [10]:
matrix

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [13]:
matrix1 = np.matrix([4, 5, 6, 1, 2, 3, 7, 8, 9]).reshape(3,3)

In [14]:
matrix1

matrix([[4, 5, 6],
        [1, 2, 3],
        [7, 8, 9]])

In [15]:
np.array_equal(matrix, matrix1)

False